FROM nginx:latest

COPY ./public-html/index.html /usr/local/apache2/htdocs/
# COPY index.html /usr/share/nginx/html

COPY ./public-html/linux.png /usr/local/apache2/htdocs/
# COPY linux.png /usr/share/nginx/html

EXPOSE 80 443 	

CMD ["nginx", "-g", "daemon off;"]
